AIA/urls.py
from django.urls import path, include

from . import views

app_name = 'AIA'

urlpatterns = [
    path( '', views.index, name='index'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('AIA/', include('AIA.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    path( '', views.index, name='index'),
    # ex: /polls/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),

]

AIA/models.py
from django.db import models

# Create your models here.

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text
        
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

AIA/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.http import Http404
from django.shortcuts import render,get_object_or_404,redirect
from django.contrib.auth.decorators import login_required
from django.conf import settings

# @login_required
def index(request):

    if not request.user.is_authenticated:
        return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))

    template = loader.get_template('AIA/index.html')
    context = {

    }
    return HttpResponse(template.render( context ,request))
    # return HttpResponse('hello world')

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.http import Http404
from django.shortcuts import render,get_object_or_404
from django.urls import reverse


from .models import Question,Choice

# Create your views here.

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    template = loader.get_template('polls/index.html')
    context = {
        'latest_question_list': latest_question_list,
    }
    return HttpResponse(template.render(context, request))

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

AIA/templates/AIA/index.html
{% load static %}


<!DOCTYPE html>
<html>
<head>
<script src="{% static 'AIA/myScript.js' %}"></script>
<link rel="stylesheet" type="text/css" href="{% static 'AIA/style.css' %}">

</head>
<body>

<!--
<p id='demo'>THIS IS DEMO TEXT.</p>
<button class="cutton">Click Me</button>
<button class="cutton" onclick="myFunction()">try it</button>
 -->

<div class='big_canvas'>
    <div class='aia_title'>
        <p>AIA紅白合戰</p>
    </div>
    <div class='odds'>
        <p> 紅 / 白</p>
        <span class='odds_red'>1 </span>
        <span class='odds_mark'> : <span>
        <span class='odds_white'>5.12</span>
    </div>
    <div class='pools'>
        <button class='pool' id='pool_red' onclick="pool_button(this)">已下注：</br>
            <span id='text_pool_red'>0</span></br>
            <span>紅</span>
        </button>
        <button class='pool' id='pool_white' onclick="pool_button(this)">已下注：</br>
            <span id='text_pool_white'>0</span></br>
            <span>白</span>
        </button>
    </div>
    <div class='bet_amount'>
        <p> 下注金額: <span id='amount'>0</span></p>
    </div>
    <div class='buttons_amount'>
        <button class='button_amount' value=100 onclick="bet_button(this)">100</button>
        <button class='button_amount' value=500 onclick="bet_button(this)">500</button>
        <button class='button_amount' value=1000 onclick="bet_button(this)">1000</button>
        <button class='button_amount' value=-1 onclick="bet_button(this)">清除</button>
    </div>
    <div class='balance_block'>
        <p> 剩餘金額: <span class='balance' id='balance_count'>5000</span></p>
    </div>



</div>


</body>
</html>

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">


{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}